### ISSUE TITLE
using lobe in website 

### ISSUE THREAD

**Issue by saurav1423** [lobe/android-bootstrap#15]
Hey, I want to use lobe in my next MERN stack project, but I don't know how to do that exactly. In the documentation I found a link for the demo project "https://github.com/lobe/web-bootstrap" but sadly it's throwing a 404 page.

**Comment by lemillermicrosoft** [comment]
Coming *very* soon! Had to take it down for some improvements. Sorry for that confusion and hope it can still help out.
