### ISSUE TITLE
Exported TFLite model from Lobe not working in Android Studio

### ISSUE THREAD

**Issue by rescog** [lobe/android-bootstrap#17]
The app is loading correctly on Windows in Android Studio 4.1.3, but the smartphone camera fails to predict classes. The green bar shows only one class and always the same, while the same model in Lobe works just fine.

**Comment by lemillermicrosoft** [comment]
We've just updated this bootstrap in #18 . Could you pull latest and see if the issue remains? Also suggest exporting a new Speed model (go to project settings to confirm) from Lobe again.

**Comment by lemillermicrosoft** [comment]
Will close this for now, please re-activate or file a new issue if there are problems with the latest changes.

**Comment by rescog** [comment]
I'm trying right now and it seems to work with my model! Thank you 👍
