### ISSUE TITLE
error: cannot find symbol

### ISSUE THREAD

**Issue by masapasa** [lobe/android-bootstrap#7]
/android-bootstrap/lobe_android/app/src/main/java/com/example/test/tflite/
TFLiteObjectDetectionAPIModel.java:266: error: cannot find symbol
    if (tfLite != null) tfLite.setUseNNAPI(isChecked);
                              ^
  symbol:   method setUseNNAPI(boolean)
  location: variable tfLite of type Interpreter

**Comment by bperel** [comment]
Same here. If I comment the faulty line, the app launches but nothing happens apart from showing a button with the text "default".

**Comment by christli7** [comment]
I'm having the exact same issue too!
![image](https://user-images.githubusercontent.com/73643273/97558634-f52a8180-1a0e-11eb-8358-446abb3deb6f.png)

**Comment by Hollywood42** [comment]
Same here on Windows and Ubuntu. If I delete that area I can get it to run on my phone with the default model but not with my own. If I place my own in the app will build but crashes when I launch it.

**Comment by adammenges** [comment]
This should be fixed now! The method we used before got depicted at some point, see:

https://www.tensorflow.org/lite/api_docs/java/org/tensorflow/lite/Interpreter
